# Generated by Django 4.2.1 on 2023-05-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors_Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Id', models.IntegerField(null=True)),
                ('doctor_Id', models.IntegerField(null=True)),
                ('doctor_Name', models.TextField(max_length=100, null=True)),
                ('patient_Name', models.TextField(max_length=100, null=True)),
                ('medicine_Name', models.TextField(max_length=100, null=True)),
                ('medicine_Dossage', models.IntegerField(null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('patient_Age', models.IntegerField(null=True)),
                ('tests_To_Done', models.IntegerField(blank=True, null=True)),
                ('date_Of_Birth', models.DateField(blank=True, null=True)),
                ('diagnosed_With', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, default='Noo', null=True)),
                ('signature', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Id', models.IntegerField()),
                ('patient_Name', models.TextField(max_length=100, null=True)),
                ('disease', models.TextField(max_length=100, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('patient_Age', models.IntegerField(null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('patient_Email', models.EmailField(max_length=254)),
                ('patient_Ph_No', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
